name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_job:
    name: Build Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: ['18.x']
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.JS ${{ matrix.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node_version }}
    - name: npm install, build
      run: |
        npm i
        npm run build
    - name: release to github
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ci-${{ github.run_number }}
        release_name: CI-Release ${{ github.run_number }}
        body: |
          Auto Building Release by Github CI
        draft: false
        prerelease: false
